### ISSUE TITLE
Setup NextCloud

### ISSUE THREAD

**Issue by ramereth** [osuosl-cookbooks/proj-seagl#1]
We need to setup a new VM called `seagl-nextcloud` which will host a NextCloud instance:

Specs:
- 4G RAM
- 100G Disk

OSL TODO's:
- [x] Create new `osl-nextcloud` cookbook to manage the service as a whole (We'll want to make this reusable for other projects down the road
- [x] Create a `nextcloud` recipe in this cookbook the `seagl-nextcloud` VM
- [x] Setup HAProxy endpoint with https
- [x] Deploy VM

**Comment by altsalt** [comment]
Hi, checking in on the status of this.

**Comment by ramereth** [comment]
I have a student who's been working on getting the core pieces together for installing and managing the instance. Making slow but good progress.

**Comment by strugee** [comment]
@ramereth any updates here?

**Comment by ramereth** [comment]
@strugee I was just working on reviewing the PR for this! I think we're getting very close, perhaps a few weeks away?

**Comment by strugee** [comment]
Wonderful! Thank you 🎉

**Comment by strugee** [comment]
@ramereth did this end up landing?

**Comment by pasimko** [comment]
Hi! We're giving the resource its final review right now, and beginning to set up the recipe for `proj-seagl::nextcloud`. Is there a vhost you are planning on using for deployment?

**Comment by strugee** [comment]
Amazing! I think `cloud.seagl.org` should work. We can just CNAME this to OSUOSL, or I'm happy to set up records directly too

**Comment by altsalt** [comment]
Hi, checking in on the status of this. Thanks for all of your efforts!

**Comment by pasimko** [comment]
We're working on some upstream issues that this uncovered - once those are polished the cookbook will be ready for deployment.

**Comment by ramereth** [comment]
Apologies for the delay on this and I've been meaning to get you an update as well.

So we were able to deploy this and then we ran into a problem with the fact that EPEL Modular was removed upstream (which we were depending on). I had been tracking that, but hadn't realized that we were relying on that for our Nextcloud implementation. We were also running into some issues with how our configuration management that required several [upstream changes](https://github.com/sous-chefs/apache2/pull/792) and downstream with our own cookbooks.

I have refactored our original implementation to use the tarball installation method which will give us some more flexibility. We are in the process of finalizing this refactor and will then get this going again.

With that in mind, NextCloud 26 was just released just over a month ago. Do you want to go with that or 25 since it was so recent?

Thanks again for your patience!

**Comment by strugee** [comment]
Thanks for the update @ramereth, we really appreciate it. We've all been there and it's no fun 🥴

26.0.1 is already out so I don't really see a major reason to stick with 25?

**Comment by ramereth** [comment]
@strugee finally got this closer but I have a few questions before we move forward:
- What domain do you want the emails to be coming from?
- Do you have a prefer for the "mail from" address? By default it's `noreply`
- Is the max filesize for uploads 1G okay, or should we increase it?

**Comment by strugee** [comment]
> What domain do you want the emails to be coming from?

cloud.seagl.org seems fine? We can either CNAME this to you so you can authorize SPF/DKIM if you want to mail through OSUOSL infra, or we can coordinate getting Nextcloud delivering through our Mailu instance (#8).

> Do you have a prefer for the "mail from" address? By default it's `noreply`

Meh, I don't and I doubt anyone else on our side does either

> Is the max filesize for uploads 1G okay, or should we increase it?

Good question, we'll get back to you on this one. Historically we've used Nextcloud to store footage from the conference - I'm not sure a) how big those files are (I _believe_ we have in the past uploaded 12-hour raw livestream footage for archiving) and b) whether you're willing to deal with hosting files that large anyway. Frankly this stuff isn't accessed that often, it just needs to be archived _somewhere_ (it's in AWS Glacier at the moment). I don't want to cause y'all headaches and suck up all your storage when there are less disruptive options!

**Comment by ramereth** [comment]
@strugee Can you please setup the following DNS?
```
cloud.seagl.org A 140.211.9.53
cloud.seagl.org AAAA 2605:bc80:3010:104::8cd3:935
```
This will point to our HAProxy instance which will be the https endpoint.

**Comment by strugee** [comment]
@ramereth done

**Comment by strugee** [comment]
I set the TTL to 5 minutes - once y'all have this rolled out and stable we can raise

**Comment by pasimko** [comment]
We've created an admin user for you on the server - Do you have a GPG key and email we can send the credentials to?

**Comment by strugee** [comment]
alex@strugee.net, https://strugee.net/pubkey.asc

**Comment by pasimko** [comment]
```
pub   rsa4096 2014-06-21 [SC] [expired: 2023-03-04]
      C46D8E7A3F13AD1C8EC6784843BF769C4ACA8B96
```
It seems this key is expired - I can just attach the credentials in an email and you can change them afterwards. Otherwise, let me know your preferred encrypted channel.

**Comment by strugee** [comment]
> It seems this key is expired - I can just attach the credentials in an email and you can change them afterwards. Otherwise, let me know your preferred encrypted channel.

Hah, whoops - sorry about that. I never really use PGP if I can help it.

I'm totally fine with just changing the creds after I receive them - probably good practice anyway. If you feel uncomfortable without an encrypted channel though feel free to DM me on Matrix. @alex:strugee.net

**Comment by strugee** [comment]
Creds changed, sorry for the delay. Some initial questions:

* Is this production-ready? Any reason we shouldn't start using it now?
* What's the backup situation?
* Nextcloud-originated emails are going to spam, probably because of our SPF policies. What IPs/DKIM keys do we need to allowlist?
* I see a pending Nextcloud upgrade in `/index.php/settings/admin/overview` - should we apply these, or will OSUOSL?
* On the same page I see a warning about an unsupported MySQL version; is this expected?
* We'd like to use Nextcloud's Collabora Online integration, or something like it - something like Google Docs provides. Any recommendations? We could install the Collabora Online built-in CODE server app, for example, but I don't know what the performance would be like.

Thank you so much for your hard work on this! I'm so so excited and this is going to be a huge help to us.

**Comment by ramereth** [comment]
> Creds changed, sorry for the delay. Some initial questions:
> 
> * Is this production-ready? Any reason we shouldn't start using it now?

Yes, I think this should be ready. Let us know if you notice anything that needs
tweaking however.

> * What's the backup situation?

The database is automatically backed up. I just added the VM backups as well.

> * Nextcloud-originated emails are going to spam, probably because of our SPF
>   policies. What IPs/DKIM keys do we need to allowlist?

You can add 'include:_spf.osuosl.org' to your SPF record if you would like. The
other option is to just change the mail routing to go through your servers. We
currently have that it set to go through our email servers and would need to
change it on our end.

> * I see a pending Nextcloud upgrade in `/index.php/settings/admin/overview` -
>  should we apply these, or will OSUOSL?

Please let us handle that as I don't know how well that upgrade will work given
how we have it setup.

> * On the same page I see a warning about an unsupported MySQL version; is this expected?

Yes, we have a long term plan to getting that upgraded.

> * We'd like to use Nextcloud's Collabora Online integration, or something like
> it - something like Google Docs provides. Any recommendations? We could
> install the Collabora Online built-in CODE server app, for example, but I
> don't know what the performance would be like.

Is [this](https://collabora-online-for-nextcloud.readthedocs.io/en/latest/install/) what you're referring to? I think we'd prefer going the route with deploying via docker or packages. From my quick reading, this would run under a different domain correct?

> Thank you so much for your hard work on this! I'm so so excited and this is
> going to be a huge help to us.

No problem! Thank you for your patience while we were getting this setup.

**Comment by strugee** [comment]
> You can add 'include:_spf.osuosl.org' to your SPF record if you would like.

This worked, thank you!

> Please let us handle that as I don't know how well that upgrade will work given
> how we have it setup.

Understood.

> Yes, we have a long term plan to getting that upgraded.

:+1: sounds good, just wanted to double-check.

> Is [this](https://collabora-online-for-nextcloud.readthedocs.io/en/latest/install/) what you're referring to? I think we'd prefer going the route with deploying via docker or packages. From my quick reading, this would run under a different domain correct?

Yeah, that's what I was talking about. Nextcloud IMO isn't really great at communicating the office stuff - https://nextcloud.com/office/ has some more marketing material that kinda talks about it. And there's a few other options too like e.g. https://nextcloud.com/onlyoffice/, although AFAICT Collabora Online is the one they kinda nudge you towards? And Collabora Online uses liberated document formats too.

To be honest I never fully got either of them working super well, and it's been a few years since I looked at them, but IIRC yes, you run Collabora Online on a separate domain and then point Nextcloud at it as the backend. Again though I could be wrong since it's been a while.

**Comment by strugee** [comment]
Quick question: we want to kill the admin account I was emailed in favor of making individual users admins - primarily because then we can all have individual 2FA. I assume there isn't a problem with deleting that user? (Or I can just disable it)

Also, let me know if you want a separate issue for the office editing stuff.

**Comment by ramereth** [comment]
> Quick question: we want to kill the admin account I was emailed in favor of making individual users admins - primarily because then we can all have individual 2FA. I assume there isn't a problem with deleting that user? (Or I can just disable it)

I don't believe we need it to do upgrades, but just in case please just disable it for now.

> Also, let me know if you want a separate issue for the office editing stuff; I realize that's a decent project on its own and not just a feature request.

Yes, please create a separate issue for that and expectations for when you'd like it deployed by.

**Comment by ramereth** [comment]
@strugee I have upgraded NextCloud to 26.0.4. Can you please verify that everything looks normal now? This is the first production upgrade and I'm concerned we may still need to work out some kinks. I noticed it did this during the upgrade so I wasn't sure if it brought those back properly:
```
            Disabled incompatible app: announcementcenter
            Disabled incompatible app: calendar
            Disabled incompatible app: contacts
            Disabled incompatible app: deck
            Disabled incompatible app: files_external_gdrive
            Disabled incompatible app: forms
            Disabled incompatible app: impersonate
            Disabled incompatible app: integration_mastodon
            Disabled incompatible app: jitsi
            Disabled incompatible app: notes
            Disabled incompatible app: polls
            Disabled incompatible app: quota_warning
            Disabled incompatible app: tasks
            Disabled incompatible app: twofactor_admin
            Disabled incompatible app: twofactor_nextcloud_notification
            Disabled incompatible app: twofactor_reminder
            Disabled incompatible app: twofactor_webauthn
            Disabled incompatible app: welcome
```

**Comment by strugee** [comment]
> I don't believe we need it to do upgrades, but just in case please just disable it for now.

Done.

> Yes, please create a separate issue for that and expectations for when you'd like it deployed by.

Filed #11 👍 

> @strugee I have upgraded NextCloud to 26.0.4. Can you please verify that everything looks normal now? This is the first production upgrade and I'm concerned we may still need to work out some kinks. I noticed it did this during the upgrade so I wasn't sure if it brought those back properly:

Looks OK AFAICT, and I sent out an announcement through Announcement Center too telling people to report problems. As for the logs, I see that on my personal Nextcloud too - I've never quite figured out what exactly the situation is there but I don't think they matter. All those apps are still enabled AFAICT.

**Comment by ramereth** [comment]
@strugee shall we go ahead and close this issue? Have we addressed everything with the initial setup?

**Comment by strugee** [comment]
Ack, missed this question. Yeah I think we're good to close! Thank you!
