### ISSUE TITLE
Setup project and accounts to OpenStack

### ISSUE THREAD

**Issue by ramereth** [osuosl-cookbooks/proj-seagl#3]
We need to setup a new "SeaGL" project and add any user accounts who will be administrating these systems. They will be managing a few VMs on their own so this will give them the flexibility. 

**SeaGL admins: Please provide public gpg keys so we can send you encrypted files with username/passwords on them.**

**Comment by OniLink** [comment]
I've set up the "SeaGL" project on OpenStack. Would you like to have one administrative account for managing it or one account per person?

@osuosl-cookbooks/seagl

**Comment by OniLink** [comment]
Pinging again

@osuosl-cookbooks/seagl

**Comment by sntxrr** [comment]
Hi, for now, we'd like to have one account per person. You can find my pub key here: https://keybase.io/sntxrr/pgp_keys.asc

**Comment by OniLink** [comment]
I have created your account and emailed your login information to you.

**Comment by sntxrr** [comment]
I've received it, decrypted it and been able to successfully login. Thank you!

**Comment by altsalt** [comment]
@AndrewKvalheim @strugee ?

**Comment by OniLink** [comment]
And don't forget to send your public key if you want an account so I can securely send your login information.

**Comment by AndrewKvalheim** [comment]
Yes, I probably should have access. Thanks.

[https://andrew.kvalhe.im/🔓](https://andrew.kvalhe.im/%F0%9F%94%93)

**Comment by strugee** [comment]
Same. https://strugee.net/gpg

**Comment by OniLink** [comment]
I have sent both of you your login information. Please confirm you have received it and can log in.

**Comment by AndrewKvalheim** [comment]
Logged in successfully, thanks.

**Comment by strugee** [comment]
Apologies, I've had COVID recently and am not caught up on stuff - will try to confirm this login tonight!

**Comment by OniLink** [comment]
@strugee Oof, I'm so sorry you caught COVID! Hope you feel better soon!

**Comment by strugee** [comment]
Thanks very much! Just logged into OpenStack successfully, thank you :rocket:

**Comment by OniLink** [comment]
That's good to hear! It seems like that is everyone so I am closing this now. Let me know if anyone else needs to get an account made.
